title: 王智慧
subtitle: 前端学习者
description: 目前用github & jekyll搭建个人博客.

author: Meloor
email: 13667065039@163.com
avatar: assets/images/me.jpg

baseurl: ""
url: "https://meloor.github.io"

# Social settings
#facebook_url: https://github.com/Meloor
github_url: https://github.com/Meloor
#linkedin_url: https://github.com/Meloor
#csdn_url: https://blog.csdn.net/Meloor
#twitter_url: https://github.com/Meloor

# SEO settiongs
google_analytics: UA-112211352-1

# Build settings
remote_theme: meloor/mySecondPage
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]
